### ISSUE TITLE
VT100 option in menu?

### ISSUE THREAD

**Issue by BRFud** [dhansel/VersaTerm#2]
Hi, I've recently build a Versaterm -  amazingly useful work, thank you. I was unsure why there was no VT100 setting in the menu under/Termainal Serrings/Type? I see only VT52, PETSCII and VT102/Ansi so thought I should ask.

Certainly it would be awesome to see more terminal types here as occasionally I am running into software configured to run on various Televideo terminals, Apple2 running CP/M, Osborne1, etc, which do not display correctly on Versaterm as far as I have yet discovered.

**Comment by dhansel** [comment]
As far as I understand the VT100 commands are a subset of the VT102 commands, so selecting VT102 will also support VT100. 
The VT52 actually behaves differently than the VT100/VT102 for some commands, which is why it has a separate setting.

I'm not currently planning to add support for other terminals but it should be fairly easy to do so by modifying the code in `software/src/terminal.c`. Look at functions `terminal_receive_char()` to process control sequences received by the terminal and `terminal_process_key()` to send out sequences for special keys (if necessary).

**Comment by BRFud** [comment]
Thank you for the clarification and pointer on how additional terminals could be implemented. Looks like there is the potential for Versaterm to be able to support a long list of historical terminals, if someone capable is able to expend the effort coding them. Many thanks again!
