### ISSUE TITLE
Question re trapping of function keys

### ISSUE THREAD

**Issue by okwatts** [dhansel/VersaTerm#3]
HI I have built 2 of these and quite like them for my retro hobby. I recently ran across a situation using a screen editor that uses the function keys to save and exit from it. This works under putty and Teraterm but doesn't under versaterm. Is this related to checking for F12 and are all F keys affected?

**Comment by dhansel** [comment]
As far as I know the VT100/VT102 standard did not include mappings for function keys, which is why VersaTerm does not include them either. TeraTerm and Putty also support other standards which I assume include the function keys.

If you know the ASCII sequence your editor expects for the function keys then you can use the keyboard macro function in VersaTerm to define the proper sequence:
1) press F11 (you will hear a single beep)
2) press the function key you want to re-define (best stick to F1-F10 since F11 and F12 have meaning in VersaTerm itself)
3) press the keyboard key sequence you want the function key to send
4) press F11 again (a double beep will indicate that the macro has been recorded)

Now every time you press the function key, VersaTerm will send that sequence. When you save your configuration the keyboard macros will be included.

Note that during step 3 you can send _any_ ASCII code by pressing and holding the left ALT key and then typing the three-digit (decimal) ASCII code on the _number keypad_ on your keyboard. For example: [hold down LEFT-ALT] 0 6 5 [release LEFT-ALT] will produce an upper-case A. This works at any time, not just when defining macros.

**Comment by okwatts** [comment]
Thanks for the quick response I will check this out and see. I have the
source for the editor so that should help.

**Comment by CygnusTM** [comment]
I just discovered this project and wanted to chime in here as a relative old timer. 

> As far as I know the VT100/VT102 standard did not include mappings for function keys, which is why VersaTerm does not include them either.

The original VT100-series terminals had four function keys, PF1-PF4. As far as I recall, everything I've used with VT100 emulation (going back to the 80s) maps at least those four.

**Comment by dhansel** [comment]
Thanks for the info! I had another look at the manual and don't understand how I missed
the PF1-PF4 keys before. To map F1/F2/F3/F4 to the corresponding sequences (ESC O P/Q/R/S) using macros:
1. For F1 press: F11 F1 ESC O P F11
2. For F2 press: F11 F2 ESC O Q F11
3. For F3 press: F11 F3 ESC O R F11
4. For F4 press: F11 F4 ESC O S F11

It shouldn't be hard to add the mapping natively. I'm currently away from home but will
take a look when I get back.

**Comment by dhansel** [comment]
I finally got around to implementing support for the PF1-PF4 function keys on the VT100 keyboard (using F1-F4 on regular keyboards. In the latest version the correct sequences for those keys are now produced.
