### ISSUE TITLE
can't the code to compile

### ISSUE THREAD

**Issue by soviet9922** [dhansel/VersaTerm#4]
Hi trying to get the last source + tinyusb updates compiled but can't get it to work get the error in screenshot.

![Screenshot 2023-12-05 at 21 36 51](https://github.com/dhansel/VersaTerm/assets/72182649/77b17edb-eb0f-419b-b662-45014f9677c4)

Maybe you can point out the problem or even better you may have an updated release and can upload it to this git ?.

Thanks !.

:)

**Comment by javavi** [comment]
I'm just adapting this project to a different scheme.
[image: Murmulator-VersaTerm.JPG]
I assembled the code according to the instructions in the Windows
environment.
The original project code is here:
https://github.com/dhansel/VersaTerm

ср, 6 дек. 2023 г. в 02:38, soviet9922 ***@***.***>:

**Comment by Commander1024** [comment]
I have the exact same issue.

That is after merging pico-sdk (and picodvi) origin/master into the workingdir (of the submodules), because the currently selected picosdk will otherwise fail even earlier.

Honestly I am not a genius in C in general and with rpi pico development specifically.

I did try various path modifications in software/src/keyboard.c trying to point it to: ../lib/pico-sdk/lib/tinyusb/hw/bsp/rp2040/board.h though, but no avail.

I figure the 3 months old binary .uf2 (resp. its corresponding pico-sdk) build might be fresh enough to support keyboards with USB hubs by now, but still... ;-)

**Comment by dhansel** [comment]
Sorry work has been very busy the past few weeks. I'm hoping to find some time next week to take a look at this.

The .uf2 file in the distribution should support keyboards with USB hubs though.

**Comment by dhansel** [comment]
Turns out the #include directives that the compiler complained about were not needed (even for the older version of tinyusb).
I have removed them in the git repository, so if you update your code you should be able to compile using the latest versions
of pico-sdk, tinyusb and PicoDVI.

@Commander1024 I can't reproduce any compile issues with the currently linked versions of the libraries.
Do you have any more details on what errors you are getting?

**Comment by Commander1024** [comment]
Actually it works for me now, too with updated main. Although I had to include stdint.h in xmodem.c, which it was complaining

```
diff --git a/software/src/xmodem.c b/software/src/xmodem.c
index 6c26654..183c0a8 100644
--- a/software/src/xmodem.c
+++ b/software/src/xmodem.c
@@ -17,6 +17,7 @@
 // Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 // -----------------------------------------------------------------------------
 
+#include <stdint.h>
 #include <stdio.h>
 #include <string.h>
 #include <stdlib.h>
```

**Comment by dhansel** [comment]
Thanks, I added the #include
