### ISSUE TITLE
Versaterm crash when store configuration

### ISSUE THREAD

**Issue by pinosoft** [dhansel/VersaTerm#9]
HI,
I'm trying to compile versaterm with Visual studio, it happens with follow errors, I managed to compile with the "Release" option but I have the following problem, I load the new .uf2, when I try to save the configuration in the "Manage configurations" menu, the software crashes and everything freezes.
If I load the default .uf2 file everything is fine.
Can you help me?
Thanks in advance
![Untitled](https://github.com/dhansel/VersaTerm/assets/4169643/e032cf56-2aa0-4200-b273-e2e08ab06812)

Pino

**Comment by dhansel** [comment]
I have not used Visual Studio to compile the code so I'm not sure how much I can help.
However, I do have a hunch. The Pi Pico crashes if it is executing code from SRAM memory while 
flashing another part of the SRAM (which is what happens when you save a configuration).
My [build instructions](https://github.com/dhansel/VersaTerm/tree/main/software#building-the-versaterm-firmware-from-source) include the line `cmake .. -DPICO_SDK_PATH=../lib/pico-sdk -DPICO_COPY_TO_RAM=1` where the `PICO_COPY_TO_RAM=1` setting makes sure that ALL code is copied to RAM before executing. This makes the code run faster and also prevents the crash when saving a configuration.

I do not know how to set this in Visual Studio but maybe you know or someone else can give you a hint.

**Comment by pinosoft** [comment]
Hi David,
Thank you so much for your answer, I try to compile with command line but I have this error:

![Untitled](https://github.com/dhansel/VersaTerm/assets/4169643/96d0a819-a541-4c63-8a5b-ca0753241932)

**Comment by pinosoft** [comment]
Maybe I found the error: **/usr/bin/sh: cd: /home/hansel/rpi-pico/VersaTerm**: No such file or directory
![Untitled_3](https://github.com/dhansel/VersaTerm/assets/4169643/28d2324c-2f15-450e-aaca-edd91c95fd77)

**Comment by pinosoft** [comment]
SOLVED!!!

Just add the follow row in the CMakeList.txt
set(PICO_COPY_TO_RAM 1)

Now all working well!
David, Thank you so much

**Comment by dhansel** [comment]
Glad to hear it's working - and thanks for posting the solution!
